### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by hua-zzz** [qlt315/JO-CDSD#1]
The following error occurs when running the file about  multi cost _cluster_size.m  :

出错 BScluster (第 17 行)
        clus_all = clus_state();

出错 main_cluster_size (第 129 行)
    [clus_all_T(:,:,t),~] = BScluster(sum(ch_T(:,:,t),3))

**Comment by qlt315** [comment]
Thanks so much for your feedback.  I just found a looping in the open-source version of the code appear in a wrong location, and I have modified the **main_ cluster_size.m** in the multi-user scenario.

**Comment by hua-zzz** [comment]
thank you

**Comment by hua-zzz** [comment]
OK,THANKS






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qlt315/JO-CDSD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月23日(星期天) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qlt315/JO-CDSD] Running error (Issue #1)





 
Closed #1 as completed.
